<scriptConfig name="VV_1" script="VV">
  <params>
    <param name="gridsim.opal.phases" type="int">1</param>
    <param name="gridsim.opal.vout_scale" type="string">3.0,3.0,3.0</param>
    <param name="vv.test_1_t_r" type="float">10.0</param>
    <param name="der.Opal.sec_crtl_frz_time" type="string">10.0</param>
    <param name="gridsim.opal.vin_scale" type="string">20.0,20.0,20.0</param>
    <param name="gridsim.opal.f_min" type="float">45.0</param>
    <param name="eut.f_min" type="float">56.0</param>
    <param name="eut.f_nom" type="float">60.0</param>
    <param name="gridsim.opal.freq" type="float">60.0</param>
    <param name="eut.f_max" type="float">66.0</param>
    <param name="gridsim.opal.f_max" type="float">70.0</param>
    <param name="vv.irr" type="string">100%</param>
    <param name="eut.v_low" type="float">105.6</param>
    <param name="eut.v_nom" type="float">120.0</param>
    <param name="gridsim.opal.v_nom" type="float">120.0</param>
    <param name="eut.v_high" type="float">132.0</param>
    <param name="gridsim.opal.v_max" type="float">300.0</param>
    <param name="eut.v_in_nom" type="int">400</param>
    <param name="eut.p_min" type="float">1000.0</param>
    <param name="das.opal.sample_interval" type="int">1000</param>
    <param name="eut.var_rated" type="float">2000.0</param>
    <param name="das.opal.rt_lab_version" type="string">2024.1.2</param>
    <param name="hil.opal.rt_lab_version" type="string">2024.1.2</param>
    <param name="hil.opal.hil_stop_time" type="float">3600.0</param>
    <param name="eut.p_rated" type="float">8000.0</param>
    <param name="eut.s_rated" type="float">10000.0</param>
    <param name="gridsim.opal.cin_scale" type="string">-3.32567,-3.33400,-3.327</param>
    <param name="vv.vref" type="string">All</param>
    <param name="das.opal.data_name" type="string">Data.mat</param>
    <param name="vv.test_2" type="string">Disabled</param>
    <param name="vv.test_3" type="string">Disabled</param>
    <param name="gridsim.auto_config" type="string">Disabled</param>
    <param name="pvsim.mode" type="string">Disabled</param>
    <param name="hil.opal.workspace_path" type="string">E:\Kai_Xie\RTLABWKSP\</param>
    <param name="hil.opal.project_dir_path" type="string">E:\Kai_Xie\RTLABWKSP\SVP1\SVP1.llp</param>
    <param name="das.opal.data_dir" type="string">E:\Kai_Xie\output\data</param>
    <param name="das.opal.wfm_dir" type="string">E:\Kai_Xie\output\waveform</param>
    <param name="eut.imbalance_resp" type="string">EUT response to the average of the three-phase effective (RMS)</param>
    <param name="vv.test_1" type="string">Enabled</param>
    <param name="hil.opal.rt_mode" type="string">Hardware</param>
    <param name="hil.opal.rt_lab_model" type="string">IEEE_1547_Testing</param>
    <param name="das.opal.sc_capture" type="string">No</param>
    <param name="das.opal.datalogger_ena" type="string">No</param>
    <param name="hil.opal.hil_config_compile" type="string">No</param>
    <param name="vv.mode" type="string">Normal</param>
    <param name="der.mode" type="string">Opal</param>
    <param name="gridsim.mode" type="string">Opal</param>
    <param name="das.mode" type="string">Opal</param>
    <param name="hil.mode" type="string">Opal-RT</param>
    <param name="das.opal.map" type="string">Opal_Fast_1547</param>
    <param name="das.opal.wfm_chan_list" type="string">PhaseJump</param>
    <param name="hil.opal.target_name" type="string">RTServer</param>
    <param name="hil.opal.rt_lab_project" type="string">SVP1.llp</param>
    <param name="eut.phases" type="string">Three phase</param>
    <param name="hil.opal.hil_config" type="string">True</param>
    <param name="hil.opal.hil_config_open" type="string">Yes</param>
    <param name="hil.opal.hil_config_stop_sim" type="string">Yes</param>
    <param name="hil.opal.hil_config_load" type="string">Yes</param>
    <param name="hil.opal.hil_config_execute" type="string">Yes</param>
  </params>
</scriptConfig>
